### PR TITLE
fd-find v10.1.0

### PR DESCRIPTION
**Pull request by flaviomartins**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by flaviomartins** [comment]
@conda-forge-admin, please rerender

**Comment by flaviomartins** [comment]
@conda-forge-admin, please rerender

**Comment by flaviomartins** [comment]
`fd --help
/Users/runner/miniforge3/conda-bld/fd-find_1714999598495/test_tmp/run_test.sh: line 7: /Users/runner/miniforge3/conda-bld/fd-find_1714999598495/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/fd: Bad CPU type in executable`

@dbast osx_arm64_ failing. Was not sure what this was about.

Edit: conda-build needed --not-test when cross compiling for osx_arm64.

**Comment by flaviomartins** [comment]
@dbast I think this is ready. The only thing missing is the ppc build. It timed out.

**Comment by dbast** [comment]
thanks!

**Pull request merged**
